name: mikack
description: Dart binding for Mikack
# version: 1.0.0
homepage: https://github.com/Hentioe/mikack-dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ffi: ^0.1.3

dev_dependencies:
  test: ^1.12.0
  grinder: ^0.8.3+1
